ALTER TABLE "Tool" ADD COLUMN "shortDescription" TEXT;
ALTER TABLE "Tool" ADD COLUMN "ogImageUrl" TEXT;
ALTER TABLE "Tool" ADD COLUMN "componentKey" TEXT;
ALTER TABLE "Tool" ADD COLUMN "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tool" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;
