CREATE TABLE "Comparison" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "excerpt" TEXT,
  "itemAName" TEXT NOT NULL,
  "itemBName" TEXT NOT NULL,
  "itemALogoUrl" TEXT,
  "itemBLogoUrl" TEXT,
  "itemAUrl" TEXT,
  "itemBUrl" TEXT,
  "itemAAffiliateUrl" TEXT,
  "itemBAffiliateUrl" TEXT,
  "summary" TEXT,
  "verdict" TEXT,
  "winner" TEXT,
  "comparisonTable" JSONB,
  "prosA" JSONB,
  "consA" JSONB,
  "prosB" JSONB,
  "consB" JSONB,
  "bestForA" JSONB,
  "bestForB" JSONB,
  "content" TEXT,
  "status" "PostStatus" NOT NULL DEFAULT 'DRAFT',
  "isFeatured" BOOLEAN NOT NULL DEFAULT false,
  "order" INTEGER NOT NULL DEFAULT 0,
  "seoTitle" TEXT,
  "seoDescription" TEXT,
  "canonicalUrl" TEXT,
  "ogImageUrl" TEXT,
  "noindex" BOOLEAN NOT NULL DEFAULT false,
  "publishedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "Comparison_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "Comparison_slug_key" ON "Comparison"("slug");
CREATE INDEX "Comparison_status_isFeatured_order_createdAt_idx" ON "Comparison"("status", "isFeatured", "order", "createdAt");
